from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))
	
	
class AttForm(forms.Form):
	your_att0 = forms.BooleanField(required=False)
	your_att1 = forms.BooleanField(required=False)
	your_att2 = forms.BooleanField(required=False)
	your_att3 = forms.BooleanField(required=False)
	your_att4 = forms.BooleanField(required=False)
	your_att5 = forms.BooleanField(required=False)
	your_att6 = forms.BooleanField(required=False)
	your_att7 = forms.BooleanField(required=False)
	your_att8 = forms.BooleanField(required=False)
	your_att9 = forms.BooleanField(required=False)
	your_att10 = forms.BooleanField(required=False)
	your_att11 = forms.BooleanField(required=False)
	your_att12 = forms.BooleanField(required=False)
	your_att13 = forms.BooleanField(required=False)
	your_att14 = forms.BooleanField(required=False)
	your_att15 = forms.BooleanField(required=False)
	your_att16 = forms.BooleanField(required=False)
	your_att17 = forms.BooleanField(required=False)
	your_att18 = forms.BooleanField(required=False)
	your_att19 = forms.BooleanField(required=False)
	your_att20 = forms.BooleanField(required=False)
	your_att21 = forms.BooleanField(required=False)
	your_att22 = forms.BooleanField(required=False)
	your_att23 = forms.BooleanField(required=False)
	your_att24 = forms.BooleanField(required=False)
	your_att25 = forms.BooleanField(required=False)
	your_att26 = forms.BooleanField(required=False)
	your_att27 = forms.BooleanField(required=False)
	your_att28 = forms.BooleanField(required=False)
	your_att29 = forms.BooleanField(required=False)
	your_att30 = forms.BooleanField(required=False)
	your_att31 = forms.BooleanField(required=False)
	your_att32 = forms.BooleanField(required=False)
	your_att33 = forms.BooleanField(required=False)
	your_att34 = forms.BooleanField(required=False)
	your_att35 = forms.BooleanField(required=False)
	your_att36 = forms.BooleanField(required=False)
	your_att37 = forms.BooleanField(required=False)
	your_att38 = forms.BooleanField(required=False)
	your_att39 = forms.BooleanField(required=False)
	your_att40 = forms.BooleanField(required=False)
	your_att41 = forms.BooleanField(required=False)
	your_att42 = forms.BooleanField(required=False)
	your_att43 = forms.BooleanField(required=False)
	your_att44 = forms.BooleanField(required=False)
	your_att45 = forms.BooleanField(required=False)
	your_att46 = forms.BooleanField(required=False)
	your_att47 = forms.BooleanField(required=False)
	your_att48 = forms.BooleanField(required=False)
	your_att49 = forms.BooleanField(required=False)
	your_att50 = forms.BooleanField(required=False)
	your_att51 = forms.BooleanField(required=False)
	your_att52 = forms.BooleanField(required=False)
	your_att53 = forms.BooleanField(required=False)
	your_att54 = forms.BooleanField(required=False)
	your_att55 = forms.BooleanField(required=False)
	your_att56 = forms.BooleanField(required=False)
	your_att57 = forms.BooleanField(required=False)
	your_att58 = forms.BooleanField(required=False)
	your_att59 = forms.BooleanField(required=False)
	your_att60 = forms.BooleanField(required=False)
	your_att61 = forms.BooleanField(required=False)
	your_att62 = forms.BooleanField(required=False)
	your_att63 = forms.BooleanField(required=False)
	your_att64 = forms.BooleanField(required=False)
	your_att65 = forms.BooleanField(required=False)
	your_att66 = forms.BooleanField(required=False)
	your_att67 = forms.BooleanField(required=False)
	your_att68 = forms.BooleanField(required=False)
	your_att69 = forms.BooleanField(required=False)
	your_att70 = forms.BooleanField(required=False)


class CsvImportForm(forms.Form):
    csv_file = forms.FileField()

class ChangePassword(forms.Form):
	newPassword=forms.CharField(label='New Password', max_length=100)