# Generated by Django 2.0.6 on 2018-07-28 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('att', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ManyToManyField(to='login.Attendance_cell')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday1', models.CharField(max_length=100)),
                ('Monday2', models.CharField(max_length=10)),
                ('Monday3', models.CharField(max_length=10)),
                ('Monday4', models.CharField(max_length=10)),
                ('Monday5', models.CharField(max_length=10)),
                ('Monday6', models.CharField(max_length=10)),
                ('Monday7', models.CharField(max_length=10)),
                ('Monday8', models.CharField(max_length=10)),
                ('Tuesday1', models.CharField(max_length=10)),
                ('Tuesday2', models.CharField(max_length=10)),
                ('Tuesday3', models.CharField(max_length=10)),
                ('Tuesday4', models.CharField(max_length=10)),
                ('Tuesday5', models.CharField(max_length=10)),
                ('Tuesday6', models.CharField(max_length=10)),
                ('Tuesday7', models.CharField(max_length=10)),
                ('Tuesday8', models.CharField(max_length=10)),
                ('Wednesday1', models.CharField(max_length=10)),
                ('Wednesday2', models.CharField(max_length=10)),
                ('Wednesday3', models.CharField(max_length=10)),
                ('Wednesday4', models.CharField(max_length=10)),
                ('Wednesday5', models.CharField(max_length=10)),
                ('Wednesday6', models.CharField(max_length=10)),
                ('Wednesday7', models.CharField(max_length=10)),
                ('Wednesday8', models.CharField(max_length=10)),
                ('Thursday1', models.CharField(max_length=10)),
                ('Thursday2', models.CharField(max_length=10)),
                ('Thursday3', models.CharField(max_length=10)),
                ('Thursday4', models.CharField(max_length=10)),
                ('Thursday5', models.CharField(max_length=10)),
                ('Thursday6', models.CharField(max_length=10)),
                ('Thursday7', models.CharField(max_length=10)),
                ('Thursday8', models.CharField(max_length=10)),
                ('Friday1', models.CharField(max_length=10)),
                ('Friday2', models.CharField(max_length=10)),
                ('Friday3', models.CharField(max_length=10)),
                ('Friday4', models.CharField(max_length=10)),
                ('Friday5', models.CharField(max_length=10)),
                ('Friday6', models.CharField(max_length=10)),
                ('Friday7', models.CharField(max_length=10)),
                ('Friday8', models.CharField(max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Semester'),
        ),
        migrations.AddField(
            model_name='attendance_table',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Section'),
        ),
        migrations.AddField(
            model_name='attendance_table',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Subject'),
        ),
        migrations.AddField(
            model_name='attendance_cell',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance_table',
            unique_together={('section', 'subject')},
        ),
    ]
