# Generated by Django 2.0.6 on 2018-07-28 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Friday1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Friday8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Monday8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Thursday8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Tuesday8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Wednesday8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
