# Generated by Django 2.0.6 on 2018-07-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180728_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='username',
            new_name='user',
        ),
    ]
