# Generated by Django 2.0.6 on 2018-08-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180731_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_cell',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('date',)},
        ),
    ]
